# Site settings
description: Mike Ward's CV
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mikeward9.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: mike ward
user_description: ASP.NET and Frontend Developer
user_title: ASP.NET and Frontend Developer
email: mikeward9@gmail.com
github_username:  mikeward9

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
